name: 'ci'
on:
  - push

jobs:
  test-ubuntu:
    name: test on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin init --apply --source .
      - name: Verify dotfiles
        run: chezmoi verify --source .
      - name: Check key files exist
        run: |
          test -f ~/.zshrc
          test -f ~/.bashrc
          test -f ~/.gitconfig
          test -f ~/.tmux.conf
          test -f ~/.profile
  test-macos:
    name: test on macOS
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin init --apply --source .
      - name: Verify dotfiles
        run: chezmoi verify --source .
      - name: Check key files exist
        run: |
          test -f ~/.zshrc
          test -f ~/.bashrc
          test -f ~/.gitconfig
          test -f ~/.tmux.conf
          test -f ~/.profile
