name: 'ci'
on:
  - push

jobs:
  test-ubuntu:
    name: test on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
  test-macos:
    name: test on macOS
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dotfiles
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
